### ISSUE TITLE
Http errors shouldn't respond with status 200 but 4xx

### ISSUE THREAD

**Issue by mikbry** [Zoapp/zoauth#9]
When
You send a faulty request to api
You got a response with a status=200
It should be a status=4XX (XX depending on error)

See zoauthRouter line 10

**Comment by mikbry** [comment]
Is it fixed ?

**Comment by lunika** [comment]
Nop I have the problem right now.

**Comment by lunika** [comment]
And moreover it is not possible to send something else than `500` when an error is thrown.

**Comment by mikbry** [comment]
Ok find a way to handle it nicefully.
